name: desc_blinding
channels:
  - conda-forge
dependencies:
    - python=3.9
    - git+https://github.com/LSSTDESC/firecrown.git@master
    - numpy
    - ipykernel
    - scipy
    - cosmosis >=2.5
    - astropy >=5.3.0
    - pytest
    - pip
    - pip:
      - argparse
      - sacc
    - cosmosis 
    - cosmosis-build-standard-library