[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blinding"
description = "DESC Blinding Unified Library. This is a DESC version of the Muir et al. (2021) blinding method."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
maintainers = [
    {name = "Arthur Loureiro", email = "arthur.loureiro@fysik.su.se"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.24.0",
    "scipy>=1.9.0",
    "cosmosis>=2.5",
    "astropy>=5.3.0",
    "pytest>=7.2.5",
    "argparse>=1.0",
    "sacc>=0.12",
]
keywords = ["desc", "python", "blinding", "firecrown"]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["src"]
